language: ruby
sudo: false
cache: bundler
script: bundle exec rake spec
rvm:
  - 1.9
  - 2.0
  - 2.1
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rbx-2
    - ruby-head
    - jruby-head
